name: electride_user
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  intl: ^0.17.0
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  google_maps_flutter: ^2.1.1
  cloud_firestore: ^3.1.0
  cupertino_icons: ^1.0.2 
  shared_preferences: ^2.0.5
  fluttertoast: ^8.0.8
  intl_phone_number_input: ^0.7.0+2
  provider: ^6.0.1
  velocity_x: ^3.3.0

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo/
    - assets/bottomIcon/
    - assets/images/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
